builds:
  -
    binary: consul-debug-read

    flags:
      - -trimpath 

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - 6
      - 7

archives:
  -
    name_template: >-
      {{- .ProjectName }}_v
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOs
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "arm" }}arm32-v{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}

    format: tar.gz

    files:
      - none*

    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: natemollica-nm
    name: consul-debug-read